on:
  # Trigger the workflow on push or pull request,
  # push only for the master branch
  # PR for all branches
  push:
    branches:
      - master
  pull_request:


name: Build and Test
jobs:
  build-and-test-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0
    - name: Build documentation
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        sudo wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod a+x /usr/bin/yq
        cd docs
        make html-author-mode
        grep -r "page unresolved" target/staging/docs/ && exit 1 || echo 'ok'
  build-and-test-scala:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup environment
      run: |
        make -C .github/workflows/setup setup-local-all

    - name: Cache SBT and Coursier cache
      uses: coursier/cache-action@v3

    - name: build-and-test
      env:
        SBT_OPTS: -Xms512M -Xmx2048M -Xss2M -XX:MaxMetaspaceSize=1024M
      run: |
        export PATH="$HOME/opt/sbt/bin:$PATH"
        cd scripts
        ./build-all.sh +test
